### ISSUE TITLE
Set up controller actions for users

### ISSUE THREAD

**Issue by Jabronious** [burnNturn/pubg-rails#5]

**Comment by burnNturn** [comment]
Got the basics setup, and added a field for someone to enter their pubg account.  Right now it is all done on the edit page, but I'm thinking about just doing a user/show, and edit each one individually from there, with AJAX.  Don't know if that makes sense.

**Comment by burnNturn** [comment]
A separate controller for users' actions created.  A show view created; going to use Ajax to edit each individual field.

**Comment by burnNturn** [comment]
Decided to use an edit page instead of the show page to update user info.
